export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';
export const GET_ITEM_FILTER = 'GET_ITEM_FILTER';
export const REMOVE_SEARCH_QUERY_LIST = 'REMOVE_SEARCH_QUERY_LIST';
